version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "build"
      prefix-development: "build"
      include: "scope"
    groups:
      dotnet:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "build"
      prefix-development: "build"
      include: "scope"
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "build"
      prefix-development: "build"
      include: "scope"
    groups:
      cloudflare:
        patterns:
          - 'cf'
          - 'wrangler'
          - '@cloudflare/*'

  - package-ecosystem: npm
    directory: /tools/web-e2e
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "build"
      prefix-development: "build"
      include: "scope"
    groups:
      playwright:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /tools/screenshot-generator
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "build"
      prefix-development: "build"
      include: "scope"
    groups:
      playwright:
        patterns:
          - "*"
